153 api auth
WGBH-MLA/chowda pull request #173
Opened 2023-10-12 15:25 UTC by afred

2023-10-20 16:48 UTC, mrharpo requested changes
👍 🔏 Just some minor fixes, plus I've added a few more tests.

2023-10-20 16:48 UTC, mrharpo commented on chowda/routers/sony_ci.py
> +    token: Annotated[OAuthAccessToken, Depends(verified_access_token)]
Need to check for `sync:sonyci` permissions here.

2023-10-24 21:25 UTC, afred reviewed
👍 from me. I the rest is good, then :shipit:

2023-10-24 22:48 UTC, mrharpo approved these changes
👍 👍

2023-10-25 18:28 UTC, merged